# Generated by Django 4.0.1 on 2022-01-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
