name: Test

on:
  push:
    branches:
      - main
#    paths:
#      - "app/django_first"
#      - "app/django_first/frontend"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello
        run: echo "Hello, GitHub Actions!"

  eslint:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [16.x]
    steps:
#      - uses: actions/checkout@v1
##      - name: npm install
##        working-directory: ./app/django_first/frontend
##        run: npm i --ignore-scripts
#      - uses: stefanoeb/eslint-action@1.0.2
#        with:
#          files: app/django_first/frontend/
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          files: app/django_first/frontend/
      - name: Install Packages
        run: npm install
      - name: Lint Files
        run: npm run lint

#  lint-node:
#    runs-on: ubuntu-latest
#    name: Node 16 eslint run
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 16
#      - name: Install eslint
#        run: npm install eslint
#      - name: Lint
#        run: make lint

#  python-lint:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.8", "3.9"]
#    name: Linux CI
#    steps:
#      - name: Check out source repository
#        uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }} environment
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Python environment report
#        run: python -c "import sys; print(sys.version)"
#      - name: Run ${{ matrix.python-version }} platform tests (default)
#        uses: py-actions/flake8@master
#        with:
#          path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails
#      - name: Run ${{ matrix.python-version }} platform tests (with args)
#        uses: py-actions/flake8@master
#        with:
#          update-pip: "true"
#          ignore: "F401"
#          exclude: "app/django_first/frontend"
#          max-line-length: "100"
#          args: "--quiet"
#          path: "app/django_first"
#          flake8-version: "master"
