name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello
        run: echo "Hello, GitHub Actions!"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          files: app/django_first/frontend/
      - name: Install Packages
        working-directory: ./app/django_first/frontend
        run: npm install
      - name: Lint Files
        working-directory: ./app/django_first/frontend
        run: npm run lint

  python-lint:
    name: Python Django linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          files: app/django_first/
          black: true
          flake8: true

#    strategy:
#      matrix:
#        python-version: ["3.8", "3.9"]
#    name: Linux CI
#    steps:
#      - name: Check out source repository
#        uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }} environment
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Python environment report
#        run: python -c "import sys; print(sys.version)"
#      - name: Run ${{ matrix.python-version }} platform tests (default)
#        uses: py-actions/flake8@master
#        with:
#          path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails
#      - name: Run ${{ matrix.python-version }} platform tests (with args)
#        uses: py-actions/flake8@master
#        with:
#          update-pip: "true"
#          ignore: "F401"
#          exclude: "app/django_first/frontend"
#          max-line-length: "100"
#          args: "--quiet"
#          path: "app/django_first"
#          flake8-version: "master"
